export const predefinedLots = [
    'Études - Conception',
    'Installation de chantier - Nettoyage',
    'Démolition',
    'Terrassement',
    'Maçonnerie - Gros œuvre',
    'Charpente - Couverture - Étanchéité - Zinguerie',
    'Menuiseries extérieures - Fenêtres',
    'Façade',
    'VRD - Aménagements extérieurs',
    'Isolation',
    'Plâtrerie - Cloisonnement',
    'Plomberie - Chauffage - Ventilation',
    'Climatisation',
    'Électricité',
    'Carrelage - Faïence',
    'Revêtements de sols',
    'Serrurerie - Métallerie',
    'Peinture',
    'Menuiseries intérieures - Agencement',
    'Cuisine',
];